export { default as Home } from './Home/Home'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as Single } from './Single/Single'
export { default as Write } from './Write/Write'
